language: R
cache: packages
sudo: false
warnings_are_errors: false

before_install:
  - export RGL_USE_NULL=TRUE
  - Rscript -e "setRepositories(ind=1:2)"

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - libglu1-mesa-dev
      